server:
  port: 8080
spring:
  application:
    name: crypto-invest
  datasource:
    username: postgres
    password: DjheoihfJH
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    enabled: true
    locations: "classpath:db/migration"
    default-schema: public
    create-schemas: true
    baselineOnMigrate: true
  jpa:
    database: postgresql

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
file:
  dir: "prices"
  execution-timeout: 30
